# bash_profile
PATH=~/bin:~/bin/local:$PATH #exported at bottom in mac-ports added blurb
PATH=$PATH:/Users/erict/Library/Android/sdk/tools/
export BUNDLE_PATH=.bundle/
export BUNDLE_BIN=.bundle/bin
export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future

#This file is sourced by bash when you log in interactively.
[ -f ~/dotfiles/shell/bashrc ] && source ~/dotfiles/shell/bashrc
# rvm stuff
[ -f ~/.profile ]              && source ~/.profile

case $_myos in
  Linux)
    # allow $USER to use keys. Only enter once and it will remain enabled till
    # you delete it or reboot the server
		/usr/bin/keychain $HOME/.ssh/github_rsa
	  source $HOME/.keychain/$HOSTNAME-sh
    ;;
  Darwin)
    ssh-add -A
    ;;
  *) ;;
esac

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM=xterm-256color
fi

# set display automagically, may only work when on telnet...
if [ -z "$DISPLAY" ]; then
  dis=`who am i $options | sed -e "s/(//" -e "s/\.*)//" | awk '{printf "%s", $6}'`
  case "$dis" in
    *) DISPLAY=${dis}:0.0 ;;
  esac
else
  DISPLAY=${DISPLAY%.0}
fi
export DISPLAY

__GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
source "${__GIT_PROMPT_DIR}/prompt-colors.sh"
RUBY_PROMPT='{$(~/.rvm/bin/rvm-prompt i v)}'

# non-git prompt stuff
PS1=""
# If it was successful, print a green check mark. Otherwise, print
# a red X.
if [[ $? == 0 ]]; then
    PS1+="${Green}✔ "
else
    PS1+="${Red}✘ "
fi
# If root, just print the host in red. Otherwise, print the current user
# and host in green.
if [[ $EUID == 0 ]]; then
    PS1+="${Red}\\u@\\h "
else
    PS1+="${Green}\\u@\\h "
fi
# Print the working directory and prompt marker in blue, and reset
# the text color to the default.
PS1+="${Blue}\\w ${Cyan}${RUBY_PROMPT} "
PS1+="${ResetColor}$ "

GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_FETCH_REMOTE_STATUS=1
GIT_PROMPT_THEME=Custom # use .git-prompt-colors.sh as theme
GIT_PROMPT_SHOW_UNTRACKED_FILES=normal

source "${__GIT_PROMPT_DIR}/gitprompt.sh"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

##
# Your previous /Users/erict/.bash_profile file was backed up as /Users/erict/.bash_profile.macports-saved_2016-05-19_at_14:55:35
##

# MacPorts Installer addition on 2016-05-19_at_14:55:35: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.
