#!/bin/bash
# Git pre-commit hook to check Ruby (*.rb) files for Pry binding references
# based upon https://gist.github.com/alexbevi/3436040
FILES_PATTERN='\.rb$'
FORBIDDEN='binding.pry\|require .pry.\|require .debugger.'

# xargs below returns true if grep sends empty string
# avoid this by pre-searching on ruby files
# turn on nullglob to match on 0
shopt -s nullglob
set -- *.rb
if [ "$#" -eq 0 ]; then exit 0; fi
shopt -u nullglob

git diff --cached --name-only | \
    grep -E $FILES_PATTERN | \
    GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n \
    "$FORBIDDEN" && echo 'Please remove debugger bindings\nCOMMIT REJECTED' && \
    exit 1

exit 0
